services:
  - type: web
    name: slavic-launcher-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PB_ADMIN_EMAIL
        value: admin@slavic.local
      - key: PB_ADMIN_PASSWORD
        value: changeme123
      - key: PB_URL
        value: http://0.0.0.0:8090
    autoDeploy: true